"""
HTTP MCP Server for Analyse-CV
Generated by LightOn Workflow Builder

This server exposes the workflow via HTTP REST API for integration with:
- LightOn Paradigm (MCP integration)
- Any HTTP-based MCP client

Usage:
    python -m http_server --port 8080 --bearer-token YOUR_TOKEN
"""

import argparse
import asyncio
import json
import logging
import os
from typing import Any, Optional

from dotenv import load_dotenv
from fastapi import FastAPI, Header, HTTPException, Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel
import uvicorn

from workflow import WorkflowExecutor
from paradigm_client import ParadigmClient

# Load environment variables from .env file
load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize FastAPI app
app = FastAPI(
    title="Analyse-CV MCP Server",
    description="Analyse et compare automatiquement 5 CV par rapport à une fiche de poste, en évaluant chaque candidat selon des critères pondérés et génère un rapport professionnel avec scores et recommandations.",
    version="1.0.0"
)

# Server configuration
BEARER_TOKEN = os.getenv("MCP_BEARER_TOKEN")
PARADIGM_API_KEY = os.getenv("PARADIGM_API_KEY")
PARADIGM_BASE_URL = os.getenv("PARADIGM_BASE_URL", "https://paradigm.lighton.ai")


class ToolListResponse(BaseModel):
    """Response model for tool listing"""
    tools: list[dict]


class ToolCallRequest(BaseModel):
    """Request model for tool execution"""
    name: str
    arguments: dict


class ToolCallResponse(BaseModel):
    """Response model for tool execution"""
    content: list[dict]


def verify_bearer_token(authorization: Optional[str]) -> bool:
    """
    Verify the bearer token from Authorization header.

    Args:
        authorization: Authorization header value

    Returns:
        bool: True if token is valid
    """
    if not BEARER_TOKEN:
        # If no token is configured, allow all requests (development mode)
        logger.warning("No bearer token configured - allowing all requests")
        return True

    if not authorization:
        return False

    # Extract token from "Bearer <token>" format
    parts = authorization.split()
    if len(parts) != 2 or parts[0].lower() != "bearer":
        return False

    return parts[1] == BEARER_TOKEN


@app.get("/")
@app.post("/")
async def root():
    """Health check endpoint"""
    return {
        "status": "ok",
        "service": "Analyse-CV MCP Server",
        "version": "1.0.0"
    }


@app.get("/health")
@app.post("/health")
async def health():
    """Health check endpoint"""
    return {"status": "healthy"}


@app.get("/tools")
async def list_tools(authorization: Optional[str] = Header(None)) -> ToolListResponse:
    """
    List all available tools.

    This endpoint is called by Paradigm to discover available MCP tools.
    """
    # Verify authentication
    if not verify_bearer_token(authorization):
        raise HTTPException(status_code=401, detail="Invalid or missing bearer token")

    logger.info("Listing available tools")

    tools = [
        {
            "name": "analyse-cv",
            "description": "Analyse et compare automatiquement 5 CV par rapport à une fiche de poste, en évaluant chaque candidat selon des critères pondérés et génère un rapport professionnel avec scores et recommandations.\n\nThis tool executes a complete workflow using the LightOn Paradigm API.\n\nInput parameters:\n- file_paths: Chemins complets des fichiers locaux a analyser (ex: C:\\Documents\\cv.pdf) (required)\n- query: Question ou demande d'analyse (optionnel) (optional)\n\nOutput format:\nJSON object containing the workflow results, including any analysis, extracted data, or generated content.",
            "inputSchema": {"type": "object", "properties": {"file_paths": {"type": "array", "description": "Chemins complets des fichiers locaux a analyser (ex: C:\\Documents\\cv.pdf)", "items": {"type": "string"}}, "query": {"type": "string", "description": "Question ou demande d'analyse (optionnel)"}}, "required": ["file_paths"]}
        }
    ]

    return ToolListResponse(tools=tools)


@app.post("/tools/call")
async def call_tool(
    request: ToolCallRequest,
    authorization: Optional[str] = Header(None)
) -> ToolCallResponse:
    """
    Execute a tool.

    This endpoint is called by Paradigm to execute the workflow.

    Args:
        request: Tool call request with name and arguments
        authorization: Bearer token for authentication

    Returns:
        Tool execution result
    """
    # Verify authentication
    if not verify_bearer_token(authorization):
        raise HTTPException(status_code=401, detail="Invalid or missing bearer token")

    logger.info("Tool call request: {{}}".format(json.dumps({{
        "name": request.name,
        "arguments": request.arguments
    }}, ensure_ascii=False)))

    # Verify tool name
    if request.name != "analyse-cv":
        raise HTTPException(
            status_code=404,
            detail="Unknown tool: {{}}".format(request.name)
        )

    try:
        # Validate Paradigm API key
        if not PARADIGM_API_KEY:
            raise ValueError("PARADIGM_API_KEY not found in environment variables. Please check your .env file.")

        # Initialize Paradigm client
        paradigm_client = ParadigmClient(
            api_key=PARADIGM_API_KEY,
            base_url=PARADIGM_BASE_URL
        )

        # Initialize workflow executor
        executor = WorkflowExecutor(paradigm_client)

        # Execute workflow
        logger.info("Executing workflow with arguments: {{}}".format(
            json.dumps(request.arguments, ensure_ascii=False)
        ))

        result = await executor.execute(**request.arguments)

        logger.info("Workflow execution completed successfully")

        # Format response according to MCP specification
        response = ToolCallResponse(
            content=[
                {{
                    "type": "text",
                    "text": json.dumps(result, ensure_ascii=False, indent=2)
                }}
            ]
        )

        return response

    except Exception as e:
        logger.error("Workflow execution failed: {{}}".format(str(e)))

        # Return error as MCP response
        error_response = ToolCallResponse(
            content=[
                {{
                    "type": "text",
                    "text": json.dumps({{
                        "error": str(e),
                        "status": "failed"
                    }}, ensure_ascii=False, indent=2)
                }}
            ]
        )

        return error_response


@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    """Global exception handler"""
    logger.error("Unhandled exception: {{}}".format(str(exc)))
    return JSONResponse(
        status_code=500,
        content={{
            "error": "Internal server error",
            "detail": str(exc)
        }}
    )


def main():
    """Main entry point for HTTP server"""
    parser = argparse.ArgumentParser(description="HTTP MCP Server for Analyse-CV")
    parser.add_argument(
        "--port",
        type=int,
        default=8080,
        help="Port to listen on (default: 8080)"
    )
    parser.add_argument(
        "--host",
        type=str,
        default="0.0.0.0",
        help="Host to bind to (default: 0.0.0.0)"
    )
    parser.add_argument(
        "--bearer-token",
        type=str,
        help="Bearer token for authentication (overrides MCP_BEARER_TOKEN env var)"
    )

    args = parser.parse_args()

    # Override bearer token if provided via command line
    if args.bearer_token:
        global BEARER_TOKEN
        BEARER_TOKEN = args.bearer_token
        logger.info("Using bearer token from command line")
    elif BEARER_TOKEN:
        logger.info("Using bearer token from environment")
    else:
        logger.warning("No bearer token configured - server will accept all requests")

    # Log server configuration
    logger.info("Starting HTTP MCP Server for Analyse-CV")
    logger.info("Host: {{}}".format(args.host))
    logger.info("Port: {{}}".format(args.port))
    logger.info("Paradigm API URL: {{}}".format(PARADIGM_BASE_URL))

    # Start server
    uvicorn.run(
        app,
        host=args.host,
        port=args.port,
        log_level="info"
    )


if __name__ == "__main__":
    main()
