"""
MCP Server for Analyse-CV using fastapi-mcp
Generated by LightOn Workflow Builder

This server exposes the workflow via proper MCP protocol for integration with:
- LightOn Paradigm (MCP integration)
- Claude Desktop
- Any MCP-compatible client

Usage:
    python -m mcp_server --port 8080
"""

import argparse
import asyncio
import logging
import os
from typing import List, Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi_mcp import FastApiMCP
from pydantic import BaseModel, Field
import uvicorn

from workflow import WorkflowExecutor
from paradigm_client import ParadigmClient

# Load environment variables from .env file
load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize FastAPI app
app = FastAPI(
    title="Analyse-CV MCP Server",
    description="Analyse et compare automatiquement 5 CV par rapport à une fiche de poste, en évaluant chaque candidat selon des critères pondérés et génère un rapport professionnel avec scores et recommandations.",
    version="1.0.0"
)

# Server configuration
PARADIGM_API_KEY = os.getenv("PARADIGM_API_KEY")
PARADIGM_BASE_URL = os.getenv("PARADIGM_BASE_URL", "https://paradigm.lighton.ai")


# Request/Response models
class AnalyseRequest(BaseModel):
    """Request model for CV analysis"""
    file_paths: List[str] = Field(
        ...,
        description="Chemins complets des fichiers locaux a analyser (ex: C:\\Documents\\cv.pdf)"
    )
    query: Optional[str] = Field(
        None,
        description="Question ou demande d'analyse (optionnel)"
    )


class AnalyseResponse(BaseModel):
    """Response model for CV analysis"""
    result: dict = Field(..., description="Analysis results")
    status: str = Field(..., description="Execution status")


# FastAPI endpoint
@app.post(
    "/analyse-cv",
    operation_id="analyse_cv",
    summary="Analyse et compare des CVs",
    description="Analyse et compare automatiquement 5 CV par rapport à une fiche de poste, en évaluant chaque candidat selon des critères pondérés et génère un rapport professionnel avec scores et recommandations.",
    response_model=AnalyseResponse
)
async def analyse_cv(request: AnalyseRequest) -> AnalyseResponse:
    """
    Analyse and compare CVs against a job description.

    This endpoint executes a complete workflow using the LightOn Paradigm API.
    """
    try:
        # Validate Paradigm API key
        if not PARADIGM_API_KEY:
            raise HTTPException(
                status_code=500,
                detail="PARADIGM_API_KEY not configured on server"
            )

        logger.info(f"Executing workflow for {len(request.file_paths)} files")

        # Initialize Paradigm client
        paradigm_client = ParadigmClient(
            api_key=PARADIGM_API_KEY,
            base_url=PARADIGM_BASE_URL
        )

        # Initialize workflow executor
        executor = WorkflowExecutor(paradigm_client)

        # Execute workflow
        result = await executor.execute(
            file_paths=request.file_paths,
            query=request.query
        )

        logger.info("Workflow execution completed successfully")

        return AnalyseResponse(
            result=result,
            status="success"
        )

    except Exception as e:
        logger.error(f"Workflow execution failed: {str(e)}")
        raise HTTPException(
            status_code=500,
            detail=f"Workflow execution failed: {str(e)}"
        )


# Health check endpoint
@app.get("/health")
async def health():
    """Health check endpoint"""
    return {"status": "healthy"}


# Initialize and mount MCP server
mcp = FastApiMCP(app)
mcp.mount_http()  # This mounts the MCP protocol at /mcp endpoint

logger.info("MCP server mounted at /mcp endpoint")
logger.info(f"Paradigm API URL: {PARADIGM_BASE_URL}")
logger.info("Server is ready to accept MCP connections")


def main():
    """Main entry point for MCP server"""
    parser = argparse.ArgumentParser(description="MCP Server for Analyse-CV")
    parser.add_argument(
        "--port",
        type=int,
        default=8080,
        help="Port to listen on (default: 8080)"
    )
    parser.add_argument(
        "--host",
        type=str,
        default="0.0.0.0",
        help="Host to bind to (default: 0.0.0.0)"
    )

    args = parser.parse_args()

    logger.info(f"Starting MCP Server for Analyse-CV")
    logger.info(f"Host: {args.host}")
    logger.info(f"Port: {args.port}")
    logger.info(f"MCP endpoint will be available at: http://{args.host}:{args.port}/mcp")

    uvicorn.run(
        app,
        host=args.host,
        port=args.port,
        log_level="info"
    )


if __name__ == "__main__":
    main()
