"""
MCP Server for Analyse-CV
Generated by LightOn Workflow Builder

This server exposes the workflow as an MCP tool that can be used in:
- Claude Desktop
- Any MCP-compatible client
- LightOn Paradigm (when MCP support is available)
"""

import asyncio
import json
import logging
import os
from typing import Any

from dotenv import load_dotenv
from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import Tool, TextContent

from workflow import WorkflowExecutor
from paradigm_client import ParadigmClient

# Load environment variables from .env file
load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# Initialize MCP server
app = Server("analyse-cv")


@app.list_tools()
async def list_tools() -> list[Tool]:
    """
    List all tools available in this MCP server.
    This workflow is exposed as a single tool.
    """
    return [
        Tool(
            name="analyse-cv",
            description="""Analyse et compare automatiquement 5 CV par rapport à une fiche de poste, en évaluant chaque candidat selon des critères pondérés et génère un rapport professionnel avec scores et recommandations.

This tool executes a complete workflow using the LightOn Paradigm API.

Input parameters:
- file_paths: Chemins complets des fichiers locaux a analyser (ex: C:\\Documents\\cv.pdf) (required)
- query: Question ou demande d'analyse (optionnel) (optional)

Output format:
JSON object containing the workflow results, including any analysis, extracted data, or generated content.
""",
            inputSchema={"type": "object", "properties": {"file_paths": {"type": "array", "description": "Chemins complets des fichiers locaux a analyser (ex: C:\\\\Documents\\\\cv.pdf)", "items": {"type": "string"}}, "query": {"type": "string", "description": "Question ou demande d'analyse (optionnel)"}}, "required": ["file_paths"]}
        )
    ]


@app.call_tool()
async def call_tool(name: str, arguments: Any) -> list[TextContent]:
    """
    Execute the workflow tool.

    Args:
        name: Tool name (should be analyse-cv)
        arguments: Tool arguments as defined in inputSchema

    Returns:
        List of TextContent with workflow results
    """
    if name != "analyse-cv":
        raise ValueError("Unknown tool: {}".format(name))

    try:
        logger.info("Starting workflow execution with arguments: {}".format(json.dumps(arguments, ensure_ascii=False)))

        # Get API key from environment
        api_key = os.getenv("PARADIGM_API_KEY")
        if not api_key:
            raise ValueError("PARADIGM_API_KEY not found in environment variables. Please check your .env file.")

        base_url = os.getenv("PARADIGM_BASE_URL", "https://paradigm.lighton.ai")

        # Initialize Paradigm client
        paradigm_client = ParadigmClient(api_key=api_key, base_url=base_url)

        # Initialize workflow executor
        executor = WorkflowExecutor(paradigm_client)

        # Execute workflow
        result = await executor.execute(**arguments)

        logger.info("Workflow execution completed successfully")

        # Format result as TextContent
        return [
            TextContent(
                type="text",
                text=json.dumps(result, ensure_ascii=False, indent=2)
            )
        ]

    except Exception as e:
        logger.error("Workflow execution failed: {}".format(str(e)))
        return [
            TextContent(
                type="text",
                text=json.dumps({
                    "error": str(e),
                    "status": "failed"
                }, ensure_ascii=False, indent=2)
            )
        ]


async def main():
    """Run the MCP server using stdio transport."""
    logger.info("Starting MCP server for Analyse-CV")

    async with stdio_server() as (read_stream, write_stream):
        await app.run(
            read_stream,
            write_stream,
            app.create_initialization_options()
        )


if __name__ == "__main__":
    asyncio.run(main())
