"""
Workflow Execution Logic
Generated by LightOn Workflow Builder
"""

import logging
import os
from typing import Any, Dict, List
from dotenv import load_dotenv
from paradigm_client import ParadigmClient

# Load environment variables from .env file
load_dotenv()

logger = logging.getLogger(__name__)


class WorkflowExecutor:
    """
    Executes the workflow using the Paradigm API.
    Supports multiple input modes:
    - File paths (for Claude Desktop with local files)
    - File IDs (for direct Paradigm document IDs)
    - Paradigm context (future - documents from Paradigm workspace)
    - Legacy attached_file_ids (from Workflow Builder web interface)
    """

    def __init__(self, paradigm_client: ParadigmClient):
        self.paradigm_client = paradigm_client

    async def upload_file_from_path(self, file_path: str) -> int:
        """
        Upload a file from local filesystem to Paradigm.

        Args:
            file_path: Path to the file to upload

        Returns:
            int: File ID in Paradigm

        Raises:
            FileNotFoundError: If file doesn't exist
            Exception: If upload fails
        """
        if not os.path.exists(file_path):
            raise FileNotFoundError("File not found: {}".format(file_path))

        logger.info("Uploading file: {}".format(file_path))

        # Read file content
        with open(file_path, 'rb') as f:
            file_content = f.read()

        filename = os.path.basename(file_path)

        # Upload to Paradigm
        result = await self.paradigm_client.upload_file(
            file_content=file_content,
            filename=filename,
            collection_type='private'
        )

        file_id = result.get('id') or result.get('file_id')
        logger.info("File uploaded successfully: {} (ID: {})".format(filename, file_id))

        # Wait for file to be embedded/indexed
        logger.info("Waiting for file {} to be indexed...".format(file_id))
        await self.paradigm_client.wait_for_embedding(
            file_id=file_id,
            max_wait_time=300,
            poll_interval=2
        )
        logger.info("File {} is ready".format(file_id))

        return file_id

    async def process_file_inputs(self, **kwargs) -> List[int]:
        """
        Process file inputs from various sources and return file IDs.

        Supports:
        - file_paths: List of local file paths to upload
        - cv_file_path, job_posting_file_path, etc.: Individual file paths
        - file_ids: Direct Paradigm document IDs
        - paradigm_context: Future Paradigm MCP context
        - Legacy attached_file_ids

        Returns:
            List[int]: List of file IDs ready to use
        """
        file_ids = []

        # MODE 1: File paths provided (Claude Desktop with local files)
        if 'file_paths' in kwargs and kwargs['file_paths']:
            logger.info("MODE 1: Uploading files from paths")
            for path in kwargs['file_paths']:
                file_id = await self.upload_file_from_path(path)
                file_ids.append(file_id)

        # MODE 1b: Individual file path parameters (cv_file_path, job_posting_file_path, etc.)
        elif any(k.endswith('_file_path') for k in kwargs.keys()):
            logger.info("MODE 1b: Uploading individual files from paths")
            for key, value in kwargs.items():
                if key.endswith('_file_path') and value:
                    file_id = await self.upload_file_from_path(value)
                    file_ids.append(file_id)

        # MODE 2: File IDs provided directly
        elif 'file_ids' in kwargs and kwargs['file_ids']:
            logger.info("MODE 2: Using provided file IDs")
            file_ids = [int(fid) for fid in kwargs['file_ids']]

        # MODE 3: Paradigm context (future integration)
        elif 'paradigm_context' in kwargs:
            logger.info("MODE 3: Using Paradigm context")
            context = kwargs['paradigm_context']
            file_ids = context.get('document_ids', [])

        # MODE 4: Legacy attached_file_ids (Workflow Builder web)
        else:
            logger.info("MODE 4: Using legacy attached_file_ids")
            import builtins
            if 'attached_file_ids' in globals() and globals()['attached_file_ids']:
                file_ids = globals()['attached_file_ids']
            elif hasattr(builtins, 'attached_file_ids') and builtins.attached_file_ids:
                file_ids = builtins.attached_file_ids
            else:
                logger.warning("No file inputs found")
                file_ids = []

        logger.info("Processed file inputs: {} file(s)".format(len(file_ids)))
        return file_ids

    async def execute(self, **kwargs) -> Dict[str, Any]:
        """
        Execute the workflow with given parameters.

        Automatically detects input mode and processes files accordingly.

        Args:
            **kwargs: Workflow parameters (file_paths, file_ids, or other parameters)

        Returns:
            Dict containing workflow results
        """
        try:
            # Process file inputs
            file_ids = await self.process_file_inputs(**kwargs)

            # Set attached_file_ids for legacy workflow code
            import builtins
            builtins.attached_file_ids = file_ids

            # Execute the workflow with user_input parameter
            # Extract query/user_input from kwargs, default to empty string
            user_input = kwargs.get('query', kwargs.get('user_input', ''))
            result = await execute_workflow(user_input)

            # Return structured result with file information
            return {
                "status": "success",
                "result": result,
                "files_processed": len(file_ids)
            }

        except Exception as e:
            logger.error("Workflow execution failed: {}".format(str(e)))
            raise


# Generated workflow code
import asyncio
import aiohttp
import json
import logging
import os
from typing import Optional, List, Dict, Any
import re

LIGHTON_API_KEY = os.getenv("PARADIGM_API_KEY", "your_api_key_here")
LIGHTON_BASE_URL = os.getenv("PARADIGM_BASE_URL", "https://paradigm.lighton.ai")

logger = logging.getLogger(__name__)

class ParadigmClient:
    def __init__(self, api_key: str, base_url: str = "https://paradigm.lighton.ai"):
        self.api_key = api_key
        self.base_url = base_url
        self.headers = {
            "Content-Type": "application/json",
            "Authorization": "Bearer {}".format(self.api_key)
        }
        self._session: Optional[aiohttp.ClientSession] = None
        logger.info("✅ ParadigmClient initialized: {}".format(base_url))

    async def _get_session(self) -> aiohttp.ClientSession:
        if self._session is None or self._session.closed:
            self._session = aiohttp.ClientSession()
            logger.debug("🔌 Created new aiohttp session")
        return self._session

    async def close(self):
        if self._session and not self._session.closed:
            await self._session.close()
            logger.debug("🔌 Closed aiohttp session")
            self._session = None

    async def get_file(self, file_id: int, include_content: bool = False) -> Dict[str, Any]:
        endpoint = "{}/api/v2/files/{}".format(self.base_url, file_id)
        params = {}
        if include_content:
            params["include_content"] = "true"

        try:
            logger.info("📄 Getting file info for ID {}".format(file_id))
            session = await self._get_session()
            async with session.get(endpoint, params=params, headers=self.headers) as response:
                if response.status == 200:
                    result = await response.json()
                    status = result.get('status', 'unknown')
                    filename = result.get('filename', 'N/A')
                    logger.info("✅ File {} ({}): status={}".format(file_id, filename, status))
                    return result
                elif response.status == 404:
                    error_text = await response.text()
                    logger.error("❌ File {} not found".format(file_id))
                    raise Exception("File {} not found: {}".format(file_id, error_text))
                else:
                    error_text = await response.text()
                    logger.error("❌ Get file failed: {}".format(response.status))
                    raise Exception("Get file API error {}: {}".format(response.status, error_text))
        except Exception as e:
            logger.error("❌ Get file error: {}".format(str(e)))
            raise

    async def wait_for_embedding(self, file_id: int, max_wait_time: int = 300, poll_interval: int = 2) -> Dict[str, Any]:
        try:
            logger.info("⏳ Waiting for file {} to be embedded (max={}s, interval={}s)".format(file_id, max_wait_time, poll_interval))
            elapsed = 0
            while elapsed < max_wait_time:
                file_info = await self.get_file(file_id)
                status = file_info.get('status', '').lower()
                filename = file_info.get('filename', 'N/A')

                logger.info("🔄 File {} ({}): status={} (elapsed: {}s)".format(file_id, filename, status, elapsed))

                if status == 'embedded':
                    logger.info("✅ File {} is embedded and ready!".format(file_id))
                    return file_info
                elif status == 'failed':
                    logger.error("❌ File {} embedding failed".format(file_id))
                    raise Exception("File {} embedding failed".format(file_id))

                await asyncio.sleep(poll_interval)
                elapsed += poll_interval

            logger.error("⏰ Timeout waiting for file {} after {}s".format(file_id, max_wait_time))
            raise Exception("Timeout waiting for file {} to be embedded".format(file_id))
        except Exception as e:
            logger.error("❌ Wait for embedding error: {}".format(str(e)))
            raise

    async def analyze_documents_with_polling(self, query: str, document_ids: List[int], model: Optional[str] = None, private: bool = True, max_wait_time: int = 300, poll_interval: int = 5) -> str:
        try:
            logger.info("📊 Analysis with polling: max={}s, interval={}s".format(max_wait_time, poll_interval))
            chat_response_id = await self.document_analysis_start(query, document_ids, model, private)
            elapsed = 0
            while elapsed < max_wait_time:
                try:
                    result = await self.document_analysis_get_result(chat_response_id)
                    status = result.get("status", "").lower()
                    logger.info("🔄 Polling: {} (elapsed: {}s)".format(status, elapsed))

                    if status in ["completed", "complete", "finished", "success"]:
                        analysis_result = result.get("result") or result.get("detailed_analysis")
                        if analysis_result:
                            logger.info("✅ Analysis done! ({} chars)".format(len(analysis_result)))
                            return analysis_result
                        else:
                            return "Analysis completed but no result was returned"
                    elif status in ["failed", "error"]:
                        logger.error("❌ Analysis failed: {}".format(status))
                        raise Exception("Analysis failed with status: {}".format(status))

                    await asyncio.sleep(poll_interval)
                    elapsed += poll_interval
                except Exception as e:
                    if "not found" in str(e).lower() or "404" in str(e):
                        logger.info("⏳ Still running... ({}s)".format(elapsed))
                        await asyncio.sleep(poll_interval)
                        elapsed += poll_interval
                        continue
                    else:
                        raise

            logger.error("⏰ Timeout after {}s".format(max_wait_time))
            raise Exception("Analysis timed out after {} seconds".format(max_wait_time))
        except Exception as e:
            logger.error("❌ Analysis with polling failed: {}".format(str(e)))
            return "Document analysis failed: {}".format(str(e))

    async def document_analysis_start(self, query: str, document_ids: List[int], model: Optional[str] = None, private: bool = True) -> str:
        endpoint = "{}/api/v2/chat/document-analysis".format(self.base_url)
        payload = {"query": query, "document_ids": document_ids}
        if model:
            payload["model"] = model

        try:
            logger.info("📊 Starting analysis: {}...".format(query[:50]))
            session = await self._get_session()
            async with session.post(endpoint, json=payload, headers=self.headers) as response:
                if response.status == 200:
                    result = await response.json()
                    chat_response_id = result.get("chat_response_id")
                    logger.info("✅ Analysis started: {}".format(chat_response_id))
                    return chat_response_id
                else:
                    error_text = await response.text()
                    logger.error("❌ Analysis start failed: {}".format(response.status))
                    raise Exception("Failed to start analysis: {} - {}".format(response.status, error_text))
        except Exception as e:
            logger.error("❌ Analysis start error: {}".format(str(e)))
            raise

    async def document_analysis_get_result(self, chat_response_id: str) -> Dict[str, Any]:
        endpoint = "{}/api/v2/chat/document-analysis/{}".format(self.base_url, chat_response_id)
        try:
            session = await self._get_session()
            async with session.get(endpoint, headers=self.headers) as response:
                if response.status == 200:
                    return await response.json()
                elif response.status == 404:
                    return {"status": "processing"}
                else:
                    error_text = await response.text()
                    raise Exception("Failed to get analysis result: {}".format(response.status))
        except Exception as e:
            logger.error("❌ Get result error: {}".format(str(e)))
            raise

    async def document_search(self, query: str, file_ids: Optional[List[int]] = None, workspace_ids: Optional[List[int]] = None, chat_session_id: Optional[str] = None, model: Optional[str] = None, company_scope: bool = False, private_scope: bool = True, tool: str = "DocumentSearch", private: bool = True) -> Dict[str, Any]:
        endpoint = "{}/api/v2/chat/document-search".format(self.base_url)
        payload = {"query": query, "company_scope": company_scope, "private_scope": private_scope, "tool": tool, "private": private}

        if file_ids:
            payload["file_ids"] = file_ids
        if workspace_ids:
            payload["workspace_ids"] = workspace_ids
        if chat_session_id:
            payload["chat_session_id"] = chat_session_id
        if model:
            payload["model"] = model

        try:
            logger.info("🔍 Document Search: {}... (tool={})".format(query[:50], tool))
            session = await self._get_session()
            async with session.post(endpoint, json=payload, headers=self.headers) as response:
                if response.status == 200:
                    result = await response.json()
                    logger.info("✅ Search completed: {} documents".format(len(result.get('documents', []))))
                    return result
                else:
                    error_text = await response.text()
                    logger.error("❌ Search failed: {} - {}".format(response.status, error_text))
                    raise Exception("Document search failed: {} - {}".format(response.status, error_text))
        except Exception as e:
            logger.error("❌ Search error: {}".format(str(e)))
            raise

    async def chat_completion(self, prompt: str, model: str = "alfred-sv5", system_prompt: Optional[str] = None, guided_choice: Optional[List[str]] = None, guided_json: Optional[Dict[str, Any]] = None, guided_regex: Optional[str] = None) -> str:
        endpoint = "{}/api/v2/chat/completions".format(self.base_url)
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        payload = {"model": model, "messages": messages}
        if guided_choice:
            payload["guided_choice"] = guided_choice
        if guided_json:
            payload["guided_json"] = guided_json
        if guided_regex:
            payload["guided_regex"] = guided_regex

        try:
            logger.info("💬 Chat completion: {}...".format(prompt[:50]))
            session = await self._get_session()
            async with session.post(endpoint, json=payload, headers=self.headers) as response:
                if response.status == 200:
                    result = await response.json()
                    answer = result["choices"][0]["message"]["content"]
                    logger.info("✅ Chat completed ({} chars)".format(len(answer)))
                    return answer
                else:
                    error_text = await response.text()
                    logger.error("❌ Chat failed: {}".format(response.status))
                    raise Exception("Chat completion failed: {}".format(response.status))
        except Exception as e:
            logger.error("❌ Chat error: {}".format(str(e)))
            raise

    async def upload_file(self, file_content: bytes, filename: str, collection_type: str = "private") -> Dict[str, Any]:
        endpoint = "{}/api/v2/files".format(self.base_url)
        data = aiohttp.FormData()
        data.add_field('file', file_content, filename=filename)
        data.add_field('collection_type', collection_type)
        headers = {"Authorization": "Bearer {}".format(self.api_key)}

        try:
            logger.info("📁 Uploading: {} ({} bytes)".format(filename, len(file_content)))
            session = await self._get_session()
            async with session.post(endpoint, data=data, headers=headers) as response:
                if response.status in [200, 201]:
                    result = await response.json()
                    file_id = result.get("id") or result.get("file_id")
                    logger.info("✅ File uploaded: ID={}".format(file_id))
                    return result
                else:
                    error_text = await response.text()
                    logger.error("❌ Upload failed: {}".format(response.status))
                    raise Exception("File upload failed: {}".format(response.status))
        except Exception as e:
            logger.error("❌ Upload error: {}".format(str(e)))
            raise

paradigm_client = ParadigmClient(LIGHTON_API_KEY, LIGHTON_BASE_URL)

async def execute_workflow(user_input: str) -> str:
    try:
        import builtins
        attached_files = None
        if 'attached_file_ids' in globals() and globals()['attached_file_ids']:
            attached_files = globals()['attached_file_ids']
        elif hasattr(builtins, 'attached_file_ids') and builtins.attached_file_ids:
            attached_files = builtins.attached_file_ids

        if not attached_files or len(attached_files) < 6:
            return "❌ ERREUR: Ce workflow nécessite exactement 6 fichiers PDF (1 fiche de poste + 5 CV). Veuillez uploader tous les fichiers nécessaires."

        file_ids = [int(f) for f in attached_files[:6]]
        logger.info("🚀 Démarrage analyse CV: 6 fichiers détectés")

        # ÉTAPE 1: Attendre l'indexation complète de tous les fichiers
        logger.info("⏳ ÉTAPE 1: Vérification indexation des 6 fichiers...")
        failed_files = []
        
        for i, file_id in enumerate(file_ids):
            try:
                logger.info("🔄 Vérification fichier {} ({}/{})".format(file_id, i+1, len(file_ids)))
                file_info = await paradigm_client.wait_for_embedding(
                    file_id=file_id,
                    max_wait_time=120,
                    poll_interval=2
                )
                logger.info("✅ Fichier {} indexé: {}".format(file_id, file_info.get('filename', 'N/A')))
            except Exception as e:
                logger.error("❌ Échec indexation fichier {}: {}".format(file_id, str(e)))
                failed_files.append(file_id)
                
                logger.info("⏳ Attente supplémentaire de 90s pour fichier {}...".format(file_id))
                await asyncio.sleep(90)
                
                try:
                    file_info = await paradigm_client.get_file(file_id)
                    if file_info.get('status', '').lower() == 'embedded':
                        logger.info("✅ Fichier {} finalement prêt après attente supplémentaire".format(file_id))
                        failed_files.remove(file_id)
                    else:
                        logger.error("❌ Fichier {} toujours non indexé: status={}".format(file_id, file_info.get('status')))
                except:
                    logger.error("❌ Fichier {} définitivement non accessible".format(file_id))

        if failed_files:
            return "❌ ERREUR: Fichiers non indexés: {}. L'analyse ne peut pas continuer. Veuillez réessayer avec des fichiers valides.".format(failed_files)

        logger.info("✅ ÉTAPE 1 terminée: Tous les fichiers sont indexés et prêts")

        # ÉTAPE 2: Extraire le contenu de la fiche de poste (premier fichier)
        logger.info("📊 ÉTAPE 2: Extraction fiche de poste...")
        fiche_poste_id = file_ids[0]
        
        try:
            fiche_poste_content = await paradigm_client.analyze_documents_with_polling(
                query="Extraire toutes les informations de cette fiche de poste : missions principales, compétences techniques requises, compétences comportementales souhaitées, expérience minimale requise, formation attendue, langues nécessaires, et tous autres critères de sélection mentionnés",
                document_ids=[fiche_poste_id],
                max_wait_time=180,
                poll_interval=3
            )
            
            if len(fiche_poste_content) < 500:
                logger.warning("⚠️ Extraction fiche de poste insuffisante, fallback VisionDocumentSearch...")
                fallback_result = await paradigm_client.document_search(
                    query="Extraire toutes les informations de cette fiche de poste complète",
                    file_ids=[fiche_poste_id],
                    tool="VisionDocumentSearch",
                    company_scope=False,
                    private_scope=False
                )
                fiche_poste_content = fallback_result.get('answer', fiche_poste_content)
                
        except Exception as e:
            logger.error("❌ Échec extraction fiche de poste: {}".format(str(e)))
            return "❌ ERREUR: Impossible d'extraire la fiche de poste. Vérifiez que le premier fichier est une fiche de poste valide."

        logger.info("✅ ÉTAPE 2 terminée: Fiche de poste extraite ({} chars)".format(len(fiche_poste_content)))

        # ÉTAPES 3a-3e: Extraire les informations des 5 CV en parallèle
        logger.info("🔄 ÉTAPES 3a-3e: Extraction CV des 5 candidats en parallèle...")
        cv_ids = file_ids[1:6]  # Les 5 derniers fichiers sont les CV
        
        # Préparer les tâches d'extraction en parallèle
        cv_extraction_tasks = []
        for i, cv_id in enumerate(cv_ids):
            task = extract_cv_with_fallback(cv_id, i+1)
            cv_extraction_tasks.append(task)
        
        # Exécuter toutes les extractions en parallèle avec gestion des erreurs
        cv_extractions = []
        try:
            cv_extractions = await asyncio.gather(*cv_extraction_tasks, return_exceptions=True)
        except Exception as e:
            logger.error("❌ Erreur dans extractions parallèles: {}".format(str(e)))
            return "❌ ERREUR: Échec lors de l'extraction des CV. Vérifiez que tous les fichiers sont des CV valides."

        # Vérifier les résultats d'extraction
        valid_extractions = []
        for i, result in enumerate(cv_extractions):
            if isinstance(result, Exception):
                logger.error("❌ Extraction CV {} échouée: {}".format(i+1, str(result)))
                valid_extractions.append("EXTRACTION_FAILED")
            else:
                valid_extractions.append(result)
                logger.info("✅ CV {} extrait ({} chars)".format(i+1, len(result)))

        logger.info("✅ ÉTAPES 3a-3e terminées: {} CV extraits avec succès".format(len([r for r in valid_extractions if r != "EXTRACTION_FAILED"])))

        # ÉTAPE 4: Compiler et nettoyer les résultats d'extraction
        logger.info("🧹 ÉTAPE 4: Compilation et nettoyage des extractions...")
        
        cleaned_cv_data = []
        for i, extraction in enumerate(valid_extractions):
            if extraction == "EXTRACTION_FAILED":
                cleaned_cv_data.append({
                    'id': 'Candidat {}'.format(i+1),
                    'content': 'EXTRACTION ÉCHOUÉE - Impossible d\'analyser ce CV',
                    'valid': False
                })
            elif len(extraction) < 200:
                cleaned_cv_data.append({
                    'id': 'Candidat {}'.format(i+1),
                    'content': 'EXTRACTION INSUFFISANTE - Données partielles: {}'.format(extraction[:100]),
                    'valid': False
                })
            else:
                # Nettoyage basique du contenu
                cleaned_content = clean_extraction_content(extraction, i+1)
                cleaned_cv_data.append({
                    'id': 'Candidat {}'.format(i+1),
                    'content': cleaned_content,
                    'valid': True
                })

        valid_candidates = [cv for cv in cleaned_cv_data if cv['valid']]
        logger.info("✅ ÉTAPE 4 terminée: {} candidats valides préparés pour analyse".format(len(valid_candidates)))

        if not valid_candidates:
            return "❌ ERREUR: Aucun CV n'a pu être extrait correctement. Vérifiez la qualité des fichiers uploadés."

        # ÉTAPES 5a-5e: Analyser et scorer les candidats en parallèle
        logger.info("📊 ÉTAPES 5a-5e: Évaluation des candidats en parallèle...")
        
        scoring_tasks = []
        for cv_data in cleaned_cv_data:
            if cv_data['valid']:
                task = score_candidate(fiche_poste_content, cv_data['content'], cv_data['id'])
                scoring_tasks.append((cv_data['id'], task))
            else:
                scoring_tasks.append((cv_data['id'], None))

        # Exécuter les évaluations en parallèle
        scoring_results = []
        active_tasks = [(cv_id, task) for cv_id, task in scoring_tasks if task is not None]
        
        if active_tasks:
            try:
                task_results = await asyncio.gather(*[task for cv_id, task in active_tasks], return_exceptions=True)
                
                result_index = 0
                for cv_id, task in scoring_tasks:
                    if task is None:
                        scoring_results.append((cv_id, "ÉVALUATION IMPOSSIBLE - CV non extrait"))
                    else:
                        if result_index < len(task_results):
                            result = task_results[result_index]
                            if isinstance(result, Exception):
                                scoring_results.append((cv_id, "ERREUR ÉVALUATION: {}".format(str(result))))
                            else:
                                scoring_results.append((cv_id, result))
                            result_index += 1
                        else:
                            scoring_results.append((cv_id, "ERREUR ÉVALUATION: Résultat manquant"))
                            
            except Exception as e:
                logger.error("❌ Erreur évaluations parallèles: {}".format(str(e)))
                return "❌ ERREUR: Échec lors de l'évaluation des candidats."

        logger.info("✅ ÉTAPES 5a-5e terminées: {} évaluations complétées".format(len(scoring_results)))

        # ÉTAPE 6: Compiler et nettoyer les résultats d'évaluation
        logger.info("🧹 ÉTAPE 6: Compilation des résultats d'évaluation...")
        
        compiled_evaluations = []
        for cv_id, evaluation in scoring_results:
            if "ERREUR" in evaluation or "IMPOSSIBLE" in evaluation:
                compiled_evaluations.append({
                    'candidate': cv_id,
                    'evaluation': evaluation,
                    'score': 0.0,
                    'valid': False
                })
            else:
                cleaned_eval = clean_evaluation_content(evaluation, cv_id)
                score = extract_score_from_evaluation(cleaned_eval)
                compiled_evaluations.append({
                    'candidate': cv_id,
                    'evaluation': cleaned_eval,
                    'score': score,
                    'valid': True
                })

        valid_evaluations = [e for e in compiled_evaluations if e['valid']]
        logger.info("✅ ÉTAPE 6 terminée: {} évaluations valides compilées".format(len(valid_evaluations)))

        # ÉTAPE 7: Calculer statistiques et recommendations
        logger.info("📈 ÉTAPE 7: Calcul des statistiques globales...")
        
        if valid_evaluations:
            scores = [e['score'] for e in valid_evaluations]
            avg_score = round(sum(scores) / len(scores), 1)
            
            recommendations = {
                'recommandé': [],
                'en_réserve': [],
                'non_retenu': []
            }
            
            for eval_data in valid_evaluations:
                score = eval_data['score']
                candidate = eval_data['candidate']
                if score >= 70.0:
                    recommendations['recommandé'].append(candidate)
                elif score >= 50.0:
                    recommendations['en_réserve'].append(candidate)
                else:
                    recommendations['non_retenu'].append(candidate)
        else:
            avg_score = 0.0
            recommendations = {'recommandé': [], 'en_réserve': [], 'non_retenu': []}

        from datetime import datetime
        timestamp = datetime.now().strftime("%d/%m/%Y à %H:%M:%S")
        
        stats = {
            'avg_score': avg_score,
            'recommendations': recommendations,
            'timestamp': timestamp,
            'total_candidates': len(compiled_evaluations),
            'valid_candidates': len(valid_evaluations)
        }
        
        logger.info("✅ ÉTAPE 7 terminée: Statistiques calculées (score moyen: {}%)".format(avg_score))

        # ÉTAPE 8: Générer le rapport final
        logger.info("📝 ÉTAPE 8: Génération du rapport final...")
        
        try:
            final_report = await generate_final_report(
                fiche_poste_content, 
                compiled_evaluations, 
                stats
            )
            
            logger.info("✅ ÉTAPE 8 terminée: Rapport final généré ({} chars)".format(len(final_report)))
            return final_report
            
        except Exception as e:
            logger.error("❌ Erreur génération rapport: {}".format(str(e)))
            return "❌ ERREUR: Impossible de générer le rapport final. Données partielles disponibles mais formatage échoué."

    except Exception as e:
        logger.error("❌ Erreur workflow: {}".format(str(e)))
        return "❌ ERREUR WORKFLOW: {}".format(str(e))
    finally:
        await paradigm_client.close()

async def extract_cv_with_fallback(cv_id: int, candidate_num: int) -> str:
    """Extrait un CV avec fallback VisionDocumentSearch si nécessaire"""
    try:
        logger.info("📄 Extraction CV candidat {} (fichier {})".format(candidate_num, cv_id))
        
        cv_content = await paradigm_client.analyze_documents_with_polling(
            query="Extraire toutes les informations de ce CV : nom complet, email, téléphone, formation détaillée avec diplômes et établissements, expérience professionnelle complète avec postes occupés et durées, compétences techniques incluant langages de programmation et outils, compétences comportementales, langues parlées avec niveaux, calcul du nombre total d'années d'expérience depuis le premier emploi",
            document_ids=[cv_id],
            max_wait_time=180,
            poll_interval=3
        )
        
        if len(cv_content) < 500:
            logger.warning("⚠️ Extraction CV {} insuffisante, fallback VisionDocumentSearch...".format(candidate_num))
            
            fallback_result = await paradigm_client.document_search(
                query="Extraire toutes les informations complètes de ce CV",
                file_ids=[cv_id],
                tool="VisionDocumentSearch",
                company_scope=False,
                private_scope=False
            )
            cv_content = fallback_result.get('answer', cv_content)
            
        logger.info("✅ CV candidat {} extrait ({} chars)".format(candidate_num, len(cv_content)))
        return cv_content
        
    except Exception as e:
        logger.error("❌ Extraction CV candidat {} échouée: {}".format(candidate_num, str(e)))
        raise

async def score_candidate(fiche_poste: str, cv_content: str, candidate_id: str) -> str:
    """Score un candidat par rapport à la fiche de poste"""
    try:
        logger.info("🎯 Évaluation {}...".format(candidate_id))
        
        evaluation_prompt = '''Évaluez ce candidat par rapport à la fiche de poste selon ces 6 critères avec pondérations exactes :

FICHE DE POSTE :
{}

CV DU CANDIDAT :
{}

CRITÈRES D'ÉVALUATION (notez chaque critère sur 100 points) :
1. Compétences techniques (35%) : Maîtrise des technologies, outils et méthodes demandés
2. Expérience professionnelle (30%) : Pertinence et durée de l'expérience par rapport au poste
3. Formation (15%) : Adéquation du niveau et domaine de formation
4. Compétences comportementales (10%) : Soft skills et aptitudes relationnelles
5. Langues (5%) : Niveau dans les langues requises
6. Éléments bonus (5%) : Certifications, projets personnels, spécialisations

Pour CHAQUE critère, donnez :
- Score de 0 à 100
- Justification de 2-3 phrases expliquant le score

Puis listez :
- Points forts (3-5 éléments)
- Points faibles (2-4 éléments)

Enfin, calculez le score global pondéré et affichez-le clairement.'''.format(fiche_poste[:2000], cv_content[:3000])

        evaluation = await paradigm_client.chat_completion(
            prompt=evaluation_prompt,
            system_prompt='''Tu es un expert en recrutement qui évalue des candidats.

🌍 RÈGLES DE LANGUE (CRITIQUE):
- Réponds UNIQUEMENT en FRANÇAIS
- N'utilise AUCUN mot d'une autre langue

📝 RÈGLES DE FORMATAGE:
- Utilise Markdown propre : ## pour titres, **gras** pour scores
- INTERDICTION ABSOLUE de balises entre crochets comme [ATTENTION], [SCORE], [ANALYSE]
- Écris "Points forts :" et NON "Points forts [AVANTAGES] :"
- Pas de préambule, écris directement le contenu

👤 RÈGLES POUR LES NOMS:
- TOUJOURS afficher les NOMS COMPLETS (Prénom NOM)
- NE JAMAIS utiliser uniquement prénoms ou identifiants'''
        )
        
        logger.info("✅ Évaluation {} terminée ({} chars)".format(candidate_id, len(evaluation)))
        return evaluation
        
    except Exception as e:
        logger.error("❌ Erreur évaluation {}: {}".format(candidate_id, str(e)))
        raise

def clean_extraction_content(content: str, candidate_num: int) -> str:
    """Nettoie le contenu d'extraction d'un CV"""
    # Supprime les métadonnées et commentaires d'IA
    cleaned = re.sub(r'(?i)(voici|here is|selon|based on).*?:', '', content)
    cleaned = re.sub(r'\*\*.*?\*\*:', '', cleaned)  # Remove bold headers
    cleaned = re.sub(r'^\s*-\s*', '', cleaned, flags=re.MULTILINE)
    
    # Standardise le format des noms
    name_pattern = r'(?i)nom\s*:?\s*([A-ZÁÉÈÊËÎÏÔÖÙÛÜŸÇ][a-záéèêëîïôöùûüÿç]+(?:\s+[A-ZÁÉÈÊËÎÏÔÖÙÛÜŸÇ][a-záéèêëîïôöùûüÿç]*)*)'
    name_match = re.search(name_pattern, cleaned)
    if name_match:
        name_parts = name_match.group(1).split()
        if len(name_parts) >= 2:
            formatted_name = "{} {}".format(name_parts[0].title(), " ".join(n.upper() for n in name_parts[1:]))
            cleaned = re.sub(name_pattern, "Nom : {}".format(formatted_name), cleaned, count=1)
    
    return cleaned.strip()

def clean_evaluation_content(content: str, candidate_id: str) -> str:
    """Nettoie le contenu d'évaluation d'un candidat"""
    # Supprime les balises entre crochets
    cleaned = re.sub(r'\[.*?\]', '', content)
    
    # Supprime les métadonnées d'IA
    cleaned = re.sub(r'(?i)(voici|here is).*?:', '', cleaned)
    
    # Uniformise les formats de scores
    cleaned = re.sub(r'(\d+)/100', r'**\1/100**', cleaned)
    cleaned = re.sub(r'Score\s*:?\s*(\d+)', r'**Score : \1/100**', cleaned)
    
    return cleaned.strip()

def extract_score_from_evaluation(evaluation: str) -> float:
    """Extrait le score final d'une évaluation"""
    # Cherche le score global pondéré
    patterns = [
        r'(?i)score\s+global.*?(\d+\.?\d*)',
        r'(?i)total.*?(\d+\.?\d*)',
        r'(?i)final.*?(\d+\.?\d*)',
        r'(?i)pondéré.*?(\d+\.?\d*)',
        r'(\d+\.?\d*)\s*%\s*$',
        r'(\d+\.?\d*)/100'
    ]
    
    for pattern in patterns:
        matches = re.findall(pattern, evaluation)
        if matches:
            try:
                score = float(matches[-1])  # Prend le dernier match (plus susceptible d'être le score final)
                if 0 <= score <= 100:
                    return round(score, 1)
            except ValueError:
                continue
    
    # Si aucun score trouvé, retourne 0
    return 0.0

async def generate_final_report(fiche_poste: str, evaluations: List[Dict], stats: Dict) -> str:
    """Génère le rapport final au format Markdown"""
    
    # Prépare les données pour le prompt
    evaluations_text = ""
    for eval_data in evaluations:
        evaluations_text += "=== {} ===\n".format(eval_data['candidate'])
        evaluations_text += "Score: {}/100\n".format(eval_data['score'])
        evaluations_text += "{}\n\n".format(eval_data['evaluation'][:1500])
    
    recommendations_text = ""
    for category, candidates in stats['recommendations'].items():
        if candidates:
            recommendations_text += "{}: {}\n".format(category.replace('_', ' ').title(), ', '.join(candidates))
    
    report_prompt = '''Génère un rapport professionnel d'analyse des candidatures avec ces données :

FICHE DE POSTE :
{}

ÉVALUATIONS DES CANDIDATS :
{}

STATISTIQUES :
- Score moyen : {}%
- Candidats valides : {}/{}
- Analyse effectuée le : {}

RECOMMANDATIONS PAR SEUILS :
{}

Structure le rapport ainsi :
## 📋 Fiche de Poste - Résumé

## 👥 Analyse des Candidats
[Présentation égale des 5 candidats sans classement, avec scores et justifications]

## 🎯 Recommandations par Seuils
[≥70% = Recommandé, 50-69% = En réserve, <50% = Non retenu]

## 📊 Synthèse Globale
[Statistiques et observations générales]

[Horodatage complet]'''.format(
        fiche_poste[:1000], 
        evaluations_text[:4000], 
        stats['avg_score'],
        stats['valid_candidates'],
        stats['total_candidates'],
        stats['timestamp'],
        recommendations_text
    )

    try:
        report = await paradigm_client.chat_completion(
            prompt=report_prompt,
            system_prompt='''Tu es un expert RH qui génère des rapports d'analyse de candidatures.

🌍 RÈGLES DE LANGUE (CRITIQUE):
- Réponds UNIQUEMENT en FRANÇAIS
- N'utilise AUCUN mot d'une autre langue

📝 RÈGLES DE FORMATAGE:
- Utilise Markdown propre avec emojis : ## pour titres, **gras**, - pour listes
- INTERDICTION ABSOLUE de balises entre crochets comme [RECOMMANDATION], [ANALYSE], [SCORE]
- Écris "Points forts :" et NON "Points forts [AVANTAGES] :"
- Pas de préambule ("Voici le rapport"), écris directement le contenu

👥 RÈGLES DE PRÉSENTATION:
- Présentation ÉGALE de tous les candidats, PAS de hiérarchie ni classement
- TOUJOURS afficher les NOMS COMPLETS (Prénom NOM), jamais d'abréviations
- Neutralité absolue dans la présentation entre candidats''')
        
        return report
        
    except Exception as e:
        logger.error("❌ Erreur génération rapport: {}".format(str(e)))
        
        # Fallback: génération basique du rapport
        fallback_report = generate_basic_report(fiche_poste, evaluations, stats)
        return fallback_report

def generate_basic_report(fiche_poste: str, evaluations: List[Dict], stats: Dict) -> str:
    """Génère un rapport basique en cas d'échec de l'IA"""
    
    report = "# 📋 Rapport d'Analyse des Candidatures\n\n"
    
    # Résumé fiche de poste
    report += "## 📋 Fiche de Poste - Résumé\n\n"
    report += "{}\n\n".format(fiche_poste[:500])
    
    # Analyse des candidats
    report += "## 👥 Analyse des Candidats\n\n"
    for eval_data in evaluations:
        report += "### {}\n".format(eval_data['candidate'])
        report += "**Score :** {}/100\n\n".format(eval_data['score'])
        if eval_data['valid']:
            report += "{}\n\n".format(eval_data['evaluation'][:800])
        else:
            report += "❌ {}\n\n".format(eval_data['evaluation'])
        report += "---\n\n"
    
    # Recommandations
    report += "## 🎯 Recommandations par Seuils\n\n"
    for category, candidates in stats['recommendations'].items():
        if candidates:
            emoji = "✅" if category == "recommandé" else "⚠️" if category == "en_réserve" else "❌"
            report += "{} **{}** : {}\n\n".format(emoji, category.replace('_', ' ').title(), ', '.join(candidates))
    
    # Synthèse
    report += "## 📊 Synthèse Globale\n\n"
    report += "- **Score moyen :** {}%\n".format(stats['avg_score'])
    report += "- **Candidats analysés :** {}/{}\n".format(stats['valid_candidates'], stats['total_candidates'])
    report += "- **Analyse effectuée le :** {}\n\n".format(stats['timestamp'])
    
    return report
